// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWt6l2R8elb7AnsY49hhuEbA81kMCgI1o',
    appId: '1:744647832565:web:1a98be6207e0053c41a6bc',
    messagingSenderId: '744647832565',
    projectId: 'currency-1cc11',
    authDomain: 'currency-1cc11.firebaseapp.com',
    databaseURL: 'https://currency-1cc11-default-rtdb.firebaseio.com',
    storageBucket: 'currency-1cc11.appspot.com',
    measurementId: 'G-K285SJM3Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpja5mua200Y01Gbks0ByEw6rD7duOlM',
    appId: '1:744647832565:android:8f81c52337ee462741a6bc',
    messagingSenderId: '744647832565',
    projectId: 'currency-1cc11',
    databaseURL: 'https://currency-1cc11-default-rtdb.firebaseio.com',
    storageBucket: 'currency-1cc11.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWt6l2R8elb7AnsY49hhuEbA81kMCgI1o',
    appId: '1:744647832565:web:cce014a4597d049741a6bc',
    messagingSenderId: '744647832565',
    projectId: 'currency-1cc11',
    authDomain: 'currency-1cc11.firebaseapp.com',
    databaseURL: 'https://currency-1cc11-default-rtdb.firebaseio.com',
    storageBucket: 'currency-1cc11.appspot.com',
    measurementId: 'G-ZYWXT50KZ7',
  );
}
